### ISSUE TITLE
Updating from Arquillian Persistence Extension 1 to 2

### ISSUE THREAD

**Issue by madoar** [arquillian/arquillian-extension-persistence#79]
First: thanks for your work!

Currently I'm using Arquillian Persistence Extension 1 in a project of mine, but I'm thinking about updating to APE 2. 
Are there any important things, that need to be done when updating to APE 2, or is it enough to simply update the maven dependencies to version 2.0.0?

**Comment by lordofthejars** [comment]
Thank you very much for using APE. The only thing that you might find is the change of package names to `org.arquillian.ape.rdbms` instead of the old ones. cc/ @bartoszmajsak

**Comment by madoar** [comment]
Thanks for the fast answer.
In addition I would like to ask about the content and uses of the different subprojects of APE 2.
When looking at the 2.0.0 branch I see the following subprojects:

- arquillian-ape-core
- arquillian-ape-junit-rule
- arquillian-ape-nosql
- arquillian-ape-rest
- arquillian-ape-spi
- arquillian-ape-sql

It would be quite nice if you could give a short description of their content and use and how to work with them.
I guess that the `README` should be extended with this information too.

**Comment by bartoszmajsak** [comment]
Thanks for your interest @madoar. This is what we are working on at the moment. For the time being you can have a look at functional tests to get a glimpse of what these are all about, but we will definitely make proper docs very soon.

**Comment by kovacss** [comment]
Following @madoar's question, how can I migrate from APE 1 to APE2 ?
It seems like the latest maven release was 1.0.0.Alpha7 ?
Thank you.

**Comment by bartoszmajsak** [comment]
Have a look here https://github.com/arquillian/arquillian-extension-persistence/issues/55#issuecomment-307763527

**Comment by kovacss** [comment]
Sorry I didn't see that... Thank you.
I know that it's still considered as an alpha but we maybe you could a reference in README file / documentation ?

**Comment by bartoszmajsak** [comment]
I'm working on that.

**Comment by bartoszmajsak** [comment]
Updated: https://github.com/arquillian/arquillian-extension-persistence/blob/2.0.0/README.adoc#2-migration-from-arquillian-persistence-extension-1x-to-2x

It's a good start, but we will provide more.
