### ISSUE TITLE
FlywayOptions has copy/paste error for table setting

### ISSUE THREAD

**Issue by reitzmichnicht** [arquillian/arquillian-extension-persistence#82]
Hi

Great that flyway is now part of this extensions. My first tests revealed this bug:

arquillian-extension-persistence/arquillian-ape-sql/standalone/flyway/src/main/java/org/arquillian/ape/rdbms/flyway/FlywayOptions.java

has a copy/paste error on line 151:
```
        if (this.options.containsKey(TABLE)) {
            flyway.setTable((String) this.options.get(SCHEMAS));
        }
```

Kind regards,
Michael

**Comment by bartoszmajsak** [comment]
Thanks for reporting it. Would you be interested in sending PR to `2.0.0` branch?

**Comment by lordofthejars** [comment]
Pushed to 2.0.0. It was a really fast fix. Thank you very much for reporting this.
